logging:
  level:
    root: DEBUG
  file:
    name: logs/checkin-service/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"