spring:
  application:
    name: gatewayserver

  config:
    import: optional:configserver:http://localhost:8071

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true


info:
  app:
    name: "Gateway Server"
    description: "Flight Booking Service Gateway Server"
    version: 1.0.0
