server:
  port: 3000

spring:
  application:
    name: booking-service
  cloud:
    function:
      definition: updateSeats
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
          group: ${spring.application.name}


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: booking_service
    description: "Flight Booking Service"
    version: 1.0.0
